<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PumpYaqobi.Domain\PumpYaqobi.Domain.csproj" />
    <ProjectReference Include="..\PumpYaqobi.Application\PumpYaqobi.Application.csproj" />
    <ProjectReference Include="..\PumpYaqobi.Persistence\PumpYaqobi.Persistence.csproj" />
  </ItemGroup>
</Project>
